/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Effect.java
 *
 * Created on 17.08.2012, 8:08:24
 */
package videoMixerLite.resources;

import codeanticode.glgraphics.GLTextureFilter;

/**
 *
 * @author User
 */
public class Effect extends javax.swing.JPanel {

    private GLTextureFilter filterEffect;
    
    private EffectsPanel effectsPanel;
    
    //private Core core;
    
    //private GLTextureFilter filterEffect;
    
    
    //private int effectNum;
    
    
    private videoMixerLite.resources.effects.rgba rgba;
    
    
    /** Creates new form Effect */
    public Effect() {
        initComponents();
    }
    
    
    public void init(EffectsPanel effectsPanel)
    {
        this.effectsPanel = effectsPanel;
        //this.core = core;
    }
    
    
    public void setFilterEffect(int effectNum)
    {
        
        if(effectsPanel.footageProperties != null)
        {
            filterEffect = effectsPanel.footageProperties.footage.core.getFilterEffect(effectNum);
        }
        else if(effectsPanel.channelProperties != null)
        {
            filterEffect = effectsPanel.channelProperties.channel.core.getFilterEffect(effectNum);
        }
        else if(effectsPanel.coreProperties != null)
        {
            filterEffect = effectsPanel.coreProperties.core.getFilterEffect(effectNum);
        }
        
        
        
        jLabel1.setText(filterEffect.getDescription());
        
        
        if(effectNum == 0)
        {
            rgba = new videoMixerLite.resources.effects.rgba();
            rgba.init(this, filterEffect);
            jScrollPane1.setViewportView(rgba);
        }
        
        
        
    }
    
    
    public GLTextureFilter getFilterEffect()
    {
        if(rgba != null)
        {
            rgba.setParameters();
        }
        
        return filterEffect;
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(32767, 100));
        setPreferredSize(new java.awt.Dimension(204, 100));

        jButton1.setText("Remove Effect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText(" ");

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        effectsPanel.removeEffect(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
