/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EffectsPanel.java
 *
 * Created on 16.08.2012, 23:25:13
 */
package videoMixerLite.resources;
//import javax.swing.BoxLayout;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
//import javax.swing.JPanel;
//import javax.swing.JRadioButton;

/**
 *
 * @author User
 */
public class EffectsPanel extends javax.swing.JPanel {

    public ChannelProperties channelProperties;
    
    public FootageProperties footageProperties;
    
    public CoreProperties coreProperties;
    
    private JPanel panel = new JPanel();
    
    
    /** Creates new form EffectsPanel */
    public EffectsPanel() {
        initComponents();
    }
    
    
    
    public void init(ChannelProperties channelProperties)
    {
        this.channelProperties = channelProperties;
    }
    
    
    public void init(FootageProperties footageProperties)
    {
        this.footageProperties = footageProperties;
    }
    
    public void init(CoreProperties coreProperties)
    {
        this.coreProperties = coreProperties;
    }
    
    
    
    private void setPanel()
    {
        BoxLayout b = new BoxLayout(panel, BoxLayout.Y_AXIS);
        panel.setLayout(b);
        jScrollPane1.setViewportView(panel);
    }
    
    /*
    private void addEffect(Effect effect)
    {
        panel.add(effect);
        setPanel();
    }
    */    
    
    public void removeEffect(Effect effect)
    {
        
        if(footageProperties != null)
        {
            footageProperties.footage.removeEffect(effect);
        }
        else if(channelProperties != null)
        {
            channelProperties.channel.removeEffect(effect);
        }
        else if(coreProperties != null)
        {
            coreProperties.core.removeEffect(effect);
        }
        
        
        panel.remove(effect);
        
        setPanel();
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jButton1.setText("Add Effect");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        EffectChoice effectChoice = new EffectChoice();
        int n = JOptionPane.showOptionDialog(null, 
                effectChoice, 
                "Choose Efffect", 
                JOptionPane.OK_CANCEL_OPTION,  
                JOptionPane.DEFAULT_OPTION, 
                null, null, null);
        
        
        if(n == 0 && effectChoice.num != -1)
        {
            
            //GLTextureFilter filterEffect;
            
            Effect effect = new Effect();
            effect.init(this);

            effect.setFilterEffect(effectChoice.num);
            
            if(footageProperties != null)
            {
                footageProperties.footage.addEffect(effect);
            }
            else if(channelProperties != null)
            {
                //effect.setFilterEffect(effectChoice.num);
                channelProperties.channel.addEffect(effect);
            }
            else if(coreProperties != null)
            {
                coreProperties.core.addEffect(effect);
            }
            
            
            //addEffect(effect);
            panel.add(effect);
            setPanel();
            
        }
        
        effectChoice = null;
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
