/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MovieProperties.java
 *
 * Created on 23.07.2012, 20:12:16
 */
package videoMixerLite.resources;

/**
 *
 * @author User
 */
public class MovieProperties extends javax.swing.JPanel {

    private Footage footage;
    
    
    /** Creates new form MovieProperties */
    public MovieProperties() {
        initComponents();
    }
    
    public void init(Footage footage)
    {
        this.footage = footage;
    }
    
    
    public void setActive(boolean active)
    {
        //jButton1.setEnabled(active);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Movie Properties");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(449, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
